version: "3"
services: 
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: db123
  app:
    image: vpn-node-back
    ports:
      - 13000:3000
#  openvpn:
#    cap_add:
#      - NET_ADMIN
#    image: kylemanna/openvpn
#    container_name: openvpn
#    ports:
#      - "1194:1194/udp"
#    restart: always
#    volumes:
#      - ./openvpn-data/conf:/etc/openvpn
